### ISSUE TITLE
issues with config file

### ISSUE THREAD

**Issue by nkalkounis** [hipchat/hipchat-cli#15]
I'm having issues with getting the script to read the config file in /etc/hipchat, is there anything I need to do in order to get it to read the config file?

**Comment by jimsmith** [comment]
This should be closed, it's almost 3 years old !

**Comment by dkolbly** [comment]
There is now support for a `~/.hipchat` as well, in case permissions are causing the problem and you don't have access to `/etc`.

If you are still having trouble, please re-open with some additional details.  Thanks!
