### ISSUE TITLE
where to specify the local hip chat server 

### ISSUE THREAD

**Issue by rajah1313** [hipchat/hipchat-cli#32]
i am hoping to use the script. where do i let the script know about the location of the hip chat server ?

**Comment by justdaver** [comment]
Use the -o option, for example specify -o hipchat.example.com

Or you could specify your server using the HIPCHAT_HOST env variable.

**Comment by jimsmith** [comment]
This should be closed, another one more than 1 year old.

**Comment by dkolbly** [comment]
@rajah1313 I'm closing this under the theory that the options @justdaver mentioned will work; please reopen if `-o` or HIPCHAT_HOST doesn't work for you and let me know any additional details about your use case.

Thanks!
